defaults: &defaults
  host: 127.0.0.1
  port: 27017
  options:
    w: 1
    pool_size: 1
    slave_ok: false
    ssl: false

development:
  <<: *defaults
  database: naantalaDev
  host: localhost

test: &test
  <<: *defaults
  database: naantalaTest
  host: localhost

staging:
  <<: *defaults
  uri: <%= ENV["MONGODB_URI"] %>

production:
  <<: *defaults
  uri: <%= ENV["MONGODB_URI"] %>
